import { Restaurant } from './types';

export const RESTAURANT_DATA: Restaurant[] = [
  {
    "id": 1,
    "name": "祥和蔬食料理（鎮江創始店）",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 1638,
    "city": "台北市",
    "address": "台北市中正區鎮江街1巷1號",
    "desc": "米其林必比登連續多年推薦，川式蔬食首選。",
    "lat": 25.0435,
    "lng": 121.5225,
    "link": "https://maps.google.com/?q=祥和蔬食料理+鎮江創始店",
    "phone": "02-2357-0377",
    "fb": "https://www.facebook.com/serenity2005/",
    "ig": "https://www.instagram.com/serenity_vegetarian/",
    "petFriendly": false
  },
  {
    "id": 2,
    "name": "祥和蔬食料理（慶城店）",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 2109,
    "city": "台北市",
    "address": "台北市松山區南京東路三段303巷7弄7號",
    "desc": "精緻川式蔬食，空間大，適合商務聚餐。",
    "lat": 25.0535,
    "lng": 121.545,
    "link": "https://maps.google.com/?q=祥和蔬食料理+慶城店",
    "phone": "02-2546-6188",
    "fb": "https://www.facebook.com/serenity2005/",
    "ig": "https://www.instagram.com/serenity_vegetarian/",
    "petFriendly": false
  },
  {
    "id": 3,
    "name": "小小樹食 Little Tree Food（大安店）",
    "types": [
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.3,
    "reviews": 2622,
    "city": "台北市",
    "address": "台北市大安區大安路一段116巷17號",
    "desc": "米其林綠星，佛陀碗、紅油皮蛋豆腐餃是必點。",
    "lat": 25.0415,
    "lng": 121.546,
    "link": "https://maps.google.com/?q=小小樹食+大安店",
    "phone": "02-2778-2277",
    "fb": "https://www.facebook.com/LittleTreeFood/",
    "ig": "https://www.instagram.com/littletreefood/",
    "petFriendly": true
  },
  {
    "id": 4,
    "name": "養心茶樓蔬食飲茶（松江本店）",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.3,
    "reviews": 8459,
    "city": "台北市",
    "address": "台北市中山區松江路128號2樓",
    "desc": "五星級蔬食港點，口味精緻，建議提前預約。",
    "lat": 25.0515,
    "lng": 121.5325,
    "link": "https://maps.google.com/?q=養心茶樓蔬食飲茶",
    "phone": "02-2542-8828",
    "fb": "https://www.facebook.com/yangshin2012/",
    "ig": "https://www.instagram.com/yangshin_vege/",
    "petFriendly": false
  },
  {
    "id": 5,
    "name": "不葷主義茶餐廳 台北店",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.9,
    "reviews": 11602,
    "city": "台北市",
    "address": "台北市松山區南京東路三段275號2樓",
    "desc": "人氣極高，提供川菜與港式蔬食，環境時尚。",
    "lat": 25.052,
    "lng": 121.543,
    "link": "https://maps.google.com/?q=不葷主義+台北店",
    "phone": "02-2545-9977",
    "fb": "https://www.facebook.com/veggienius21/",
    "ig": "https://www.instagram.com/veggienius21/",
    "petFriendly": false
  },
  {
    "id": 6,
    "name": "歡喜心集-台北南京店",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.8,
    "reviews": 850,
    "city": "台北市",
    "address": "台北市松山區寧安街7巷2號",
    "desc": "健康純粹蔬食，適合安靜用餐，口味清爽。",
    "lat": 25.0505,
    "lng": 121.554,
    "link": "https://maps.google.com/?q=歡喜心集+台北南京店",
    "phone": "02-2577-9292",
    "fb": "https://www.facebook.com/happyheartveg/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 7,
    "name": "有哆創意蔬食洋食舘",
    "types": [
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 1118,
    "city": "台北市",
    "address": "台北市松山區南京東路五段33號",
    "desc": "現轉型為異國火鍋/煲湯吃到飽，品牌經營穩定。",
    "lat": 25.051,
    "lng": 121.558,
    "link": "https://maps.google.com/?q=有哆創意蔬食洋食舘",
    "phone": "02-3765-3619",
    "fb": null,
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 8,
    "name": "心家純淨蔬食",
    "types": [
      "純素"
    ],
    "rating": 4.8,
    "reviews": 269,
    "city": "台北市",
    "address": "台北市松山區富錦街508號",
    "desc": "民生社區溫馨小店，全素家常菜。",
    "lat": 25.06,
    "lng": 121.562,
    "link": "https://maps.google.com/?q=心家純淨蔬食",
    "phone": "02-2369-8089",
    "fb": "https://www.facebook.com/VeganHeartHome/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 9,
    "name": "VGest 蔬食百匯（首都松山店）",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 1302,
    "city": "台北市",
    "address": "台北市松山區八德路四段658號",
    "desc": "低碳蔬食百匯，提供披薩與多國料理。",
    "lat": 25.05,
    "lng": 121.576,
    "link": "https://maps.google.com/?q=蔬食百匯+首都松山店",
    "phone": "02-2766-6123",
    "fb": null,
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 11,
    "name": "BaganHood 蔬食餐酒館",
    "types": [
      "純素"
    ],
    "rating": 4.7,
    "reviews": 1850,
    "city": "台北市",
    "address": "台北市信義區忠孝東路四段553巷46弄11號",
    "desc": "質感餐酒館，松菸商圈純素漢堡首選。",
    "lat": 25.0427,
    "lng": 121.5645,
    "link": "https://maps.google.com/?q=BaganHood+蔬食餐酒館",
    "phone": "02-3762-2557",
    "fb": "https://www.facebook.com/BaganHood/",
    "ig": "https://www.instagram.com/baganhood/",
    "petFriendly": true
  },
  {
    "id": 12,
    "name": "Plants",
    "types": [
      "純素"
    ],
    "rating": 4.6,
    "reviews": 1420,
    "city": "台北市",
    "address": "台北市大安區復興南路一段253巷10號1樓",
    "desc": "植物性、無麩質、全食物，注重健康與原味。",
    "lat": 25.0355,
    "lng": 121.5443,
    "link": "https://maps.google.com/?q=Plants+台北",
    "phone": "02-2784-5677",
    "fb": "https://www.facebook.com/plantseatery/",
    "ig": "https://www.instagram.com/plantseatery/",
    "petFriendly": true
  },
  {
    "id": 13,
    "name": "Miacucina（信義店）",
    "types": [
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 3200,
    "city": "台北市",
    "address": "台北市信義區松壽路11號2樓",
    "desc": "信義新光A11，沙拉與各式義大利麵分量極足。",
    "lat": 25.0363,
    "lng": 121.5673,
    "link": "https://maps.google.com/?q=Miacucina+信義店",
    "phone": "02-2722-3120",
    "fb": "https://www.facebook.com/Miacucinafamily/",
    "ig": "https://www.instagram.com/miacucina_tw/",
    "petFriendly": false
  },
  {
    "id": 14,
    "name": "無口小廚 Mukuchi Kitchen & Bar",
    "types": [
      "純素"
    ],
    "rating": 4.6,
    "reviews": 950,
    "city": "台北市",
    "address": "台北市大同區環河北路一段431號1樓",
    "desc": "大稻埕人氣純素拉麵。無電話，需透過官方LINE(@988nhbaa)或FB訂位。",
    "lat": 25.0622,
    "lng": 121.5088,
    "link": "https://maps.google.com/?q=無口小廚+大稻埕",
    "phone": "無電話，LINE訂位:@988nhbaa",
    "fb": "https://www.facebook.com/mukuchi2019/",
    "ig": "https://www.instagram.com/mukuchi2019/",
    "petFriendly": true
  },
  {
    "id": 15,
    "name": "三個傻瓜印度蔬食餐廳（長春店）",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 2500,
    "city": "台北市",
    "address": "台北市中山區長春路318號",
    "desc": "全台唯一全素印度料理，去五辛無蛋奶，南京店為主店。",
    "lat": 25.0548,
    "lng": 121.5412,
    "link": "https://maps.google.com/?q=三個傻瓜印度蔬食+南京店",
    "phone": "02-8770-5848",
    "fb": "https://www.facebook.com/toastcurry1/",
    "ig": "https://www.instagram.com/3idiots.restaurant/",
    "petFriendly": true
  },
  {
    "id": 17,
    "name": "陽明春天（心苑）",
    "types": [
      "純素"
    ],
    "rating": 4.6,
    "reviews": 1250,
    "city": "台北市",
    "address": "台北市士林區菁山路119-1號",
    "desc": "米其林綠星，藝術無菜單蔬食料理，環境優美。",
    "lat": 25.1442,
    "lng": 121.5631,
    "link": "https://maps.google.com/?q=陽明春天+心苑",
    "phone": "02-2862-0178",
    "fb": "https://www.facebook.com/ymspring/",
    "ig": "https://www.instagram.com/yangmingspring/",
    "petFriendly": false
  },
  {
    "id": 68,
    "name": "Miacucina（南西店）",
    "types": [
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 1850,
    "city": "台北市",
    "address": "台北市中山區南京西路14號2樓",
    "desc": "新光三越南西一館內，交通便利，深受女性喜愛。",
    "lat": 25.0525,
    "lng": 121.521,
    "link": "https://maps.google.com/?q=Miacucina+南西店",
    "phone": "02-2521-5215",
    "fb": "https://www.facebook.com/Miacucinafamily/",
    "ig": "https://www.instagram.com/miacucina_tw/",
    "petFriendly": false
  },
  {
    "id": 69,
    "name": "Miacucina（復興店）",
    "types": [
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.3,
    "reviews": 2100,
    "city": "台北市",
    "address": "台北市大安區復興南路一段107巷11號",
    "desc": "位於東區巷弄，品牌經典店點，貝果與沙拉為特色。",
    "lat": 25.043,
    "lng": 121.543,
    "link": "https://maps.google.com/?q=Miacucina+復興店",
    "phone": "02-2775-3393",
    "fb": "https://www.facebook.com/Miacucinafamily/",
    "ig": "https://www.instagram.com/miacucina_tw/",
    "petFriendly": false
  },
  {
    "id": 71,
    "name": "Miacucina（天母店）",
    "types": [
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.3,
    "reviews": 1900,
    "city": "台北市",
    "address": "台北市士林區德行西路48號",
    "desc": "天母核心商圈，氛圍悠閒，義式蔬食料理口感細緻。",
    "lat": 25.103,
    "lng": 121.523,
    "link": "https://maps.google.com/?q=Miacucina+天母店",
    "phone": "02-8866-2658",
    "fb": "https://www.facebook.com/Miacucinafamily/",
    "ig": "https://www.instagram.com/miacucina_tw/",
    "petFriendly": false
  },
  {
    "id": 31,
    "name": "蔬慕 Vegan Amore",
    "types": [
      "純素",
      "五辛素"
    ],
    "rating": 4.6,
    "reviews": 1320,
    "city": "台北市",
    "address": "台北市大同區承德路一段1號3F",
    "desc": "京站內時尚純素西餐，義大利麵口味濃厚層次豐富。",
    "lat": 25.0494,
    "lng": 121.5168,
    "link": "https://maps.google.com/?q=蔬慕+Vegan+Amore",
    "phone": "02-2555-6090",
    "fb": "https://www.facebook.com/veganamore.tw/",
    "ig": "https://www.instagram.com/veganamore.tw/",
    "petFriendly": false
  },
  {
    "id": 32,
    "name": "Herbivore Vegan",
    "types": [
      "純素",
      "五辛素"
    ],
    "rating": 4.4,
    "reviews": 980,
    "city": "台北市",
    "address": "台北市信義區松壽路21號2樓",
    "desc": "信義區質感純素餐廳，提供大份量異國風情料理。",
    "lat": 25.0358,
    "lng": 121.5675,
    "link": "https://maps.google.com/?q=Herbivore+Vegan",
    "phone": "02-2723-5368",
    "fb": "https://www.facebook.com/HerbivoreVegan/",
    "ig": "https://www.instagram.com/herbivore_vegan/",
    "petFriendly": false
  },
  {
    "id": 73,
    "name": "有麵子蔬食料理",
    "types": [
      "純素",
      "五辛素"
    ],
    "rating": 4.8,
    "reviews": 850,
    "city": "台北市",
    "address": "台北市中山區錦州街404號",
    "desc": "捷運中山國中站人氣蔬食，招牌燕麥奶拉麵與雙拼咖哩飯。",
    "lat": 25.0601,
    "lng": 121.5432,
    "link": "https://maps.google.com/?q=有麵子蔬食料理",
    "phone": "02-2933-4522",
    "fb": null,
    "ig": null,
    "petFriendly": true
  },
  {
    "id": 19,
    "name": "貓嘰咕自家烘焙咖啡",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.7,
    "reviews": 850,
    "city": "新北市",
    "address": "新北市板橋區文化路一段270巷3弄40號",
    "desc": "貓咪友善空間，純素甜點評價極高。",
    "lat": 25.0182,
    "lng": 121.4623,
    "link": "https://maps.google.com/?q=貓嘰咕自家烘焙咖啡",
    "phone": "02-8259-5556",
    "fb": "https://www.facebook.com/MaoJiGu/",
    "ig": "https://www.instagram.com/maojigu/",
    "petFriendly": true
  },
  {
    "id": 20,
    "name": "布佬廚房 Bruce's Kitchen",
    "types": [
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.3,
    "reviews": 3100,
    "city": "新北市",
    "address": "新北市新店區車子路137號",
    "desc": "新店經典蔬食，披薩與義大利麵廣受好評。",
    "lat": 24.9572,
    "lng": 121.5005,
    "link": "https://maps.google.com/?q=布佬廚房",
    "phone": "02-8666-6181",
    "fb": "https://www.facebook.com/bruceskitchentw/",
    "ig": "https://www.instagram.com/bruceskitchentw/",
    "petFriendly": true
  },
  {
    "id": 21,
    "name": "熱浪島南洋蔬食茶堂（林口店）",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 1600,
    "city": "新北市",
    "address": "新北市林口區惠民街2號",
    "desc": "南洋風味料理，肉骨茶與叻沙麵是亮點。",
    "lat": 25.0745,
    "lng": 121.3712,
    "link": "https://maps.google.com/?q=熱浪島南洋蔬食茶堂+林口店",
    "phone": "02-2608-3082",
    "fb": "https://www.facebook.com/pulau.redang3/",
    "ig": null,
    "petFriendly": true
  },
  {
    "id": 22,
    "name": "原素食府",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.2,
    "reviews": 4500,
    "city": "新北市",
    "address": "新北市板橋區府中路29之2號4樓",
    "desc": "板橋蔬食百匯名店，菜色豐富，服務親切。",
    "lat": 25.0088,
    "lng": 121.4595,
    "link": "https://maps.google.com/?q=原素食府",
    "phone": "02-2272-8999",
    "fb": "https://www.facebook.com/yuanvegetarian/",
    "ig": "https://www.instagram.com/yuanvegetarian/",
    "petFriendly": false
  },
  {
    "id": 23,
    "name": "浣花草堂（中和東坡店）",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 920,
    "city": "新北市",
    "address": "新北市中和區連城路89巷5號",
    "desc": "古典儒風裝潢，平價的中式蔬食家常料理。",
    "lat": 25.0012,
    "lng": 121.4923,
    "link": "https://maps.google.com/?q=浣花草堂+中和店",
    "phone": "02-8245-8718",
    "fb": "https://www.facebook.com/HuanHuaCaoTang/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 33,
    "name": "果然匯 板橋店",
    "types": [
      "純素",
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.6,
    "reviews": 4100,
    "city": "新北市",
    "address": "新北市板橋區中山路一段152號11樓",
    "desc": "位於板橋遠百，現煎猴頭菇排與精緻甜點是特色。",
    "lat": 25.0118,
    "lng": 121.4628,
    "link": "https://maps.google.com/?q=果然匯+板橋店",
    "phone": "02-2956-2888",
    "fb": "https://www.facebook.com/www.fruitfulfood.com.tw/",
    "ig": "https://www.instagram.com/fruitfulfood_tw/",
    "petFriendly": false
  },
  {
    "id": 34,
    "name": "寬心園 板橋中山店",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 1850,
    "city": "新北市",
    "address": "新北市板橋區中山路一段158號",
    "desc": "精緻和風蔬食，食材選用講究，適合宴客聚餐。",
    "lat": 25.0115,
    "lng": 121.463,
    "link": "https://maps.google.com/?q=寬心園+板橋中山店",
    "phone": "02-8953-2983",
    "fb": "https://www.facebook.com/easyhouse1108/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 70,
    "name": "Miacucina（裕隆城店）",
    "types": [
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.6,
    "reviews": 1200,
    "city": "新北市",
    "address": "新北市新店區中興路三段70號1樓",
    "desc": "新店裕隆城據點，環境開闊，提供質感創意西式蔬食。",
    "lat": 24.975,
    "lng": 121.546,
    "link": "https://maps.google.com/?q=Miacucina+裕隆城店",
    "phone": "02-2910-1208",
    "fb": "https://www.facebook.com/Miacucinafamily/",
    "ig": "https://www.instagram.com/miacucina_tw/",
    "petFriendly": false
  },
  {
    "id": 24,
    "name": "Monday 蔬食料理（桃園店）",
    "types": [
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.9,
    "reviews": 1704,
    "city": "桃園市",
    "address": "桃園市桃園區大有路648號",
    "desc": "桃園高人氣西式蔬食，漢堡與燉飯精緻美味。",
    "lat": 25.015,
    "lng": 121.321,
    "link": "https://maps.google.com/?q=Monday+蔬食料理",
    "phone": "03-355-6611",
    "fb": "https://www.facebook.com/mondayvegetarian/",
    "ig": null,
    "petFriendly": true
  },
  {
    "id": 25,
    "name": "入木三分 無菜單蔬食",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.6,
    "reviews": 850,
    "city": "桃園市",
    "address": "桃園市龍潭區新龍路62號",
    "desc": "禪風無菜單料理，用餐環境與食材層次俱佳。",
    "lat": 24.8621,
    "lng": 121.2134,
    "link": "https://maps.google.com/?q=入木三分+無菜單蔬食",
    "phone": "03-479-0220",
    "fb": "https://www.facebook.com/yamawood/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 27,
    "name": "艾維農歐風素食",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.7,
    "reviews": 680,
    "city": "桃園市",
    "address": "桃園市桃園區大業路一段292號1樓",
    "desc": "歐法式蔬食，擺盤美感與口味兼具。",
    "lat": 25.0088,
    "lng": 121.3155,
    "link": "https://maps.google.com/?q=艾維農歐風素食",
    "phone": "03-358-1350",
    "fb": "https://www.facebook.com/avignonrestaurant/",
    "ig": "https://www.instagram.com/avignon_veg/",
    "petFriendly": false
  },
  {
    "id": 28,
    "name": "善果林蔬食",
    "types": [
      "純素"
    ],
    "rating": 4.4,
    "reviews": 550,
    "city": "桃園市",
    "address": "桃園市中壢區環北路400號",
    "desc": "中壢純素麵食，口味家常清爽，適合全家聚餐。",
    "lat": 24.9622,
    "lng": 121.2211,
    "link": "https://maps.google.com/?q=善果林蔬食",
    "phone": "03-422-2220",
    "fb": null,
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 29,
    "name": "Veggie Joy 蔬食樂",
    "types": [
      "純素",
      "五辛素"
    ],
    "rating": 4.6,
    "reviews": 720,
    "city": "桃園市",
    "address": "桃園市蘆竹區南崁路一段112號",
    "desc": "健康導向蔬食，提供多樣化植物肉漢堡與輕食。",
    "lat": 25.0411,
    "lng": 121.2955,
    "link": "https://maps.google.com/?q=Veggie+Joy+蔬食樂",
    "phone": "03-322-2220",
    "fb": "https://www.facebook.com/veggiejoytw/",
    "ig": "https://www.instagram.com/veggiejoytw/",
    "petFriendly": true
  },
  {
    "id": 35,
    "name": "漢來蔬食 桃園店",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.6,
    "reviews": 2200,
    "city": "桃園市",
    "address": "桃園市蘆竹區南崁路一段112號6樓",
    "desc": "台茂百貨內，五星級精緻中式蔬食港點。",
    "lat": 25.0411,
    "lng": 121.2955,
    "link": "https://maps.google.com/?q=漢來蔬食+桃園店",
    "phone": "03-312-5222",
    "fb": "https://www.facebook.com/hilaivegetarian/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 36,
    "name": "果然匯 桃園統領店",
    "types": [
      "純素",
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.6,
    "reviews": 3500,
    "city": "桃園市",
    "address": "桃園市桃園區中正路61號7樓",
    "desc": "桃園統領百貨內，空間感極佳，蔬食選擇豐富多變。",
    "lat": 24.9935,
    "lng": 121.3138,
    "link": "https://maps.google.com/?q=果然匯+桃園統領店",
    "phone": "03-333-9666",
    "fb": "https://www.facebook.com/www.fruitfulfood.com.tw/",
    "ig": "https://www.instagram.com/fruitfulfood_tw/",
    "petFriendly": false
  },
  {
    "id": 37,
    "name": "籽田野菜屋",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.6,
    "reviews": 1250,
    "city": "新竹縣",
    "address": "新竹縣竹北市高鐵二路136號",
    "desc": "竹北日式風格蔬食，胡麻拉麵與烤糰子是熱門商品。",
    "lat": 24.808,
    "lng": 121.0405,
    "link": "https://maps.google.com/?q=籽田野菜屋",
    "phone": "03-668-5688",
    "fb": "https://www.facebook.com/seed.veg/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 38,
    "name": "善菓堂 SHAN GUO TANG",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 950,
    "city": "新竹縣",
    "address": "新竹縣竹北市莊敬南路188號1樓",
    "desc": "禪藝氛圍中式料理，適合正式聚餐。",
    "lat": 24.8165,
    "lng": 121.025,
    "link": "https://maps.google.com/?q=善菓堂",
    "phone": "03-667-5955",
    "fb": "https://www.facebook.com/shanguotang/",
    "ig": "https://www.instagram.com/shanguotang/",
    "petFriendly": false
  },
  {
    "id": 39,
    "name": "井町日式蔬食-新大同店",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 1500,
    "city": "新竹市",
    "address": "新竹市東區大同路136號",
    "desc": "日式風格蔬食，冷麵與炸物拼盤味道經典。",
    "lat": 24.8055,
    "lng": 120.9685,
    "link": "https://maps.google.com/?q=井町日式蔬食+新大同店",
    "phone": "03-525-3158",
    "fb": "https://www.facebook.com/JingTingVeg/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 40,
    "name": "輕揚 Veggie Delight",
    "types": [
      "純素",
      "五辛素"
    ],
    "rating": 4.5,
    "reviews": 880,
    "city": "新竹縣",
    "address": "新竹縣竹北市科大一路130號",
    "desc": "竹北創意蔬食，網美風格環境，漢堡分量充足。",
    "lat": 24.8235,
    "lng": 121.011,
    "link": "https://maps.google.com/?q=輕揚+Veggie+Delight",
    "phone": "03-558-5580",
    "fb": "https://www.facebook.com/veggiedelight.tw/",
    "ig": "https://www.instagram.com/veggiedelight.tw/",
    "petFriendly": true
  },
  {
    "id": 41,
    "name": "蔬適圈",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.7,
    "reviews": 420,
    "city": "新竹市",
    "address": "新竹市北區北大路285-1號",
    "desc": "注重天然食材原味，口味清淡自然無油膩感。",
    "lat": 24.8112,
    "lng": 120.965,
    "link": "https://maps.google.com/?q=蔬適圈",
    "phone": "03-522-0866",
    "fb": "https://www.facebook.com/vegecircle/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 42,
    "name": "寬心園 新竹竹北店",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 1650,
    "city": "新竹縣",
    "address": "新竹縣竹北市莊敬二街8號",
    "desc": "高級蔬食連鎖，套餐精緻，深受竹科聚餐喜愛。",
    "lat": 24.825,
    "lng": 121.0255,
    "link": "https://maps.google.com/?q=寬心園+新竹竹北店",
    "phone": "03-550-9716",
    "fb": "https://www.facebook.com/easyhouse1108/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 43,
    "name": "卓也小屋 蔬食餐廳",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 5600,
    "city": "苗栗縣",
    "address": "苗栗縣三義鄉雙潭村崩山下1-5號",
    "desc": "三義知名景觀蔬食，藥膳火鍋與客家手作點心是重點。",
    "lat": 24.3885,
    "lng": 120.798,
    "link": "https://maps.google.com/?q=卓也小屋+蔬食餐廳",
    "phone": "03-787-9198",
    "fb": "https://www.facebook.com/joyesanyi/",
    "ig": "https://www.instagram.com/joyesanyi/",
    "petFriendly": true
  },
  {
    "id": 44,
    "name": "禪廚蔬食餐廳",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.6,
    "reviews": 1800,
    "city": "苗栗縣",
    "address": "苗栗縣頭份市中央路726號",
    "desc": "頭份高人氣中式蔬食，創意功夫菜色深受長輩喜愛。",
    "lat": 24.6935,
    "lng": 120.902,
    "link": "https://maps.google.com/?q=禪廚蔬食餐廳",
    "phone": "03-768-8829",
    "fb": "https://www.facebook.com/ZenKitchenVeg/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 45,
    "name": "滴水坊-大明寺",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 350,
    "city": "苗栗縣",
    "address": "苗栗縣苗栗市經國路二段485號",
    "desc": "大明寺內環境肅靜，提供平價素食麵食與小餐。",
    "lat": 24.571,
    "lng": 120.825,
    "link": "https://maps.google.com/?q=大明寺+滴水坊",
    "phone": "03-732-7401",
    "fb": null,
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 46,
    "name": "荷塘居",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.3,
    "reviews": 1200,
    "city": "苗栗縣",
    "address": "苗栗縣公館鄉館南村332號",
    "desc": "優美田園景觀，精緻蔬食套餐與下午茶體驗極佳。",
    "lat": 24.498,
    "lng": 120.8215,
    "link": "https://maps.google.com/?q=荷塘居",
    "phone": "03-723-3456",
    "fb": "https://www.facebook.com/hetangju/",
    "ig": null,
    "petFriendly": true
  },
  {
    "id": 47,
    "name": "曙光蔬食",
    "types": [
      "純素",
      "五辛素"
    ],
    "rating": 4.7,
    "reviews": 650,
    "city": "宜蘭縣",
    "address": "宜蘭縣羅東鎮中正北路111號",
    "desc": "羅東高評價西式蔬食，義大利麵與燉飯口味濃郁。",
    "lat": 24.6815,
    "lng": 121.7725,
    "link": "https://maps.google.com/?q=曙光蔬食",
    "phone": "03-955-6888",
    "fb": "https://www.facebook.com/DawnVegan/",
    "ig": "https://www.instagram.com/dawnvegan/",
    "petFriendly": true
  },
  {
    "id": 48,
    "name": "綠緣居蔬食館",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 520,
    "city": "宜蘭縣",
    "address": "宜蘭縣宜蘭市女中路三段111號",
    "desc": "老字號中式蔬食，適合家族聚餐，CP值高。",
    "lat": 24.7485,
    "lng": 121.748,
    "link": "https://maps.google.com/?q=綠緣居蔬食館",
    "phone": "03-936-6888",
    "fb": null,
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 49,
    "name": "幸福蝸牛",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.6,
    "reviews": 480,
    "city": "宜蘭縣",
    "address": "宜蘭縣宜蘭市農權路三段163巷11號",
    "desc": "家常溫馨感十足，提供各式健康蔬食簡餐。",
    "lat": 24.746,
    "lng": 121.745,
    "link": "https://maps.google.com/?q=幸福蝸牛",
    "phone": "03-936-6688",
    "fb": "https://www.facebook.com/HappySnailVeg/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 50,
    "name": "一簞食 - 蔬食x生活",
    "types": [
      "純素",
      "五辛素"
    ],
    "rating": 4.8,
    "reviews": 320,
    "city": "宜蘭縣",
    "address": "宜蘭縣員山鄉尚深路122號",
    "desc": "深溝村在地小農食材，無電話，僅能透過社群私訊預約。",
    "lat": 24.735,
    "lng": 121.72,
    "link": "https://maps.google.com/?q=一簞食",
    "phone": "無電話",
    "fb": "https://www.facebook.com/yidanshi/",
    "ig": "https://www.instagram.com/yidanshi/",
    "petFriendly": true
  },
  {
    "id": 51,
    "name": "佛光山蘭陽別院 滴水坊",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 680,
    "city": "宜蘭縣",
    "address": "宜蘭縣宜蘭市中山路三段257號1樓",
    "desc": "蘭陽別院內滴水坊，平價且環境舒適明亮。",
    "lat": 24.7615,
    "lng": 121.755,
    "link": "https://maps.google.com/?q=蘭陽別院+滴水坊",
    "phone": "03-933-3888",
    "fb": null,
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 52,
    "name": "不葷主義茶餐廳 台中店",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.8,
    "reviews": 8500,
    "city": "台中市",
    "address": "台中市南屯區公益路二段21號",
    "desc": "台中旗艦店，人氣極高，素食港點口味正宗。",
    "lat": 24.1505,
    "lng": 120.65,
    "link": "https://maps.google.com/?q=不葷主義茶餐廳+台中店",
    "phone": "04-2328-8111",
    "fb": "https://www.facebook.com/veggienius21/",
    "ig": "https://www.instagram.com/veggienius21/",
    "petFriendly": false
  },
  {
    "id": 53,
    "name": "曙光居",
    "types": [
      "純素"
    ],
    "rating": 4.6,
    "reviews": 1200,
    "city": "台中市",
    "address": "台中市西屯區大墩十八街104號",
    "desc": "米其林推介手作麵食，招牌香辣麵口感厚實香辣。",
    "lat": 24.158,
    "lng": 120.6485,
    "link": "https://maps.google.com/?q=曙光居",
    "phone": "04-2329-2322",
    "fb": "https://www.facebook.com/shuguangju/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 54,
    "name": "將進酒 頂級蔬食燒肉殿",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.7,
    "reviews": 2100,
    "city": "台中市",
    "address": "台中市西區精誠五街27號",
    "desc": "頂級燒肉蔬食體驗，餐點華麗精緻，適合慶生。",
    "lat": 24.154,
    "lng": 120.656,
    "link": "https://maps.google.com/?q=將進酒+頂級蔬食燒肉殿",
    "phone": "04-2327-8012",
    "fb": "https://www.facebook.com/vgbbq/",
    "ig": "https://www.instagram.com/vgbbq/",
    "petFriendly": false
  },
  {
    "id": 55,
    "name": "Enrich restaurant & café",
    "types": [
      "純素",
      "五辛素"
    ],
    "rating": 4.6,
    "reviews": 1550,
    "city": "台中市",
    "address": "台中市西屯區大墩二十街111號",
    "desc": "高質感西式創意蔬食，推薦松露燉飯與特色溫沙拉。",
    "lat": 24.159,
    "lng": 120.6505,
    "link": "https://maps.google.com/?q=Enrich+restaurant",
    "phone": "04-2310-8386",
    "fb": "https://www.facebook.com/enrichrestaurant/",
    "ig": "https://www.instagram.com/enrich_restaurant/",
    "petFriendly": true
  },
  {
    "id": 56,
    "name": "養素庭迴轉蔬食火鍋",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 3200,
    "city": "台中市",
    "address": "台中市北屯區崇德路二段208號",
    "desc": "迴轉蔬食火鍋，食材多樣，趣味性與美味兼備。",
    "lat": 24.175,
    "lng": 120.685,
    "link": "https://maps.google.com/?q=養素庭迴轉火車蔬食火鍋",
    "phone": "04-2241-1585",
    "fb": "https://www.facebook.com/yangsuting/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 58,
    "name": "漢來蔬食 台中廣三SOGO店",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 1900,
    "city": "台中市",
    "address": "台中市西區台灣大道二段459號16樓",
    "desc": "百貨高樓層蔬食飲茶，餐點水準穩定。",
    "lat": 24.1555,
    "lng": 120.6625,
    "link": "https://maps.google.com/?q=漢來蔬食+台中廣三SOGO店",
    "phone": "04-2325-3888",
    "fb": "https://www.facebook.com/hilaivegetarian/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 59,
    "name": "斐得蔬食 秀泰台中站前店",
    "types": [
      "純素",
      "五辛素"
    ],
    "rating": 4.8,
    "reviews": 2800,
    "city": "台中市",
    "address": "台中市東區南京路66號3樓",
    "desc": "跨國風味蔬食，推薦披薩與牧羊人派。",
    "lat": 24.1365,
    "lng": 120.688,
    "link": "https://maps.google.com/?q=斐得蔬食+秀泰台中站前店",
    "phone": "04-2215-0376",
    "fb": "https://www.facebook.com/VerdureRestaurant/",
    "ig": "https://www.instagram.com/verdure_restaurant/",
    "petFriendly": false
  },
  {
    "id": 72,
    "name": "Miacucina（台中新光店）",
    "types": [
      "五辛素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.3,
    "reviews": 1500,
    "city": "台中市",
    "address": "台中市西屯區台灣大道三段301號10樓",
    "desc": "台中新光三越內，提供全系列義式蔬食與手作甜點。",
    "lat": 24.165,
    "lng": 120.644,
    "link": "https://maps.google.com/?q=Miacucina+台中新光店",
    "phone": "04-2252-8252",
    "fb": "https://www.facebook.com/Miacucinafamily/",
    "ig": "https://www.instagram.com/miacucina_tw/",
    "petFriendly": false
  },
  {
    "id": 60,
    "name": "林家素食",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.3,
    "reviews": 1100,
    "city": "彰化縣",
    "address": "彰化縣彰化市永安街252號",
    "desc": "在地傳統老店，素圓Q彈必吃。",
    "lat": 24.083,
    "lng": 120.542,
    "link": "https://maps.google.com/?q=林家素食",
    "phone": "04-726-8627",
    "fb": null,
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 61,
    "name": "清心緣蔬食坊",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 1650,
    "city": "彰化縣",
    "address": "彰化縣彰化市中華西路165號",
    "desc": "彰化吃到飽名店，各式手作料理豐富。",
    "lat": 24.075,
    "lng": 120.53,
    "link": "https://maps.google.com/?q=清心緣蔬食坊",
    "phone": "04-762-2399",
    "fb": "https://www.facebook.com/QingXinYuan/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 62,
    "name": "淘米樂蔬食園地",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 950,
    "city": "彰化縣",
    "address": "彰化縣彰化市寶山路802號",
    "desc": "庭園景致與天然蔬食，適合悠閒用餐。",
    "lat": 24.065,
    "lng": 120.555,
    "link": "https://maps.google.com/?q=淘米樂蔬食園地",
    "phone": "04-728-7132",
    "fb": "https://www.facebook.com/taomile/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 63,
    "name": "蒝味蔬食",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.6,
    "reviews": 820,
    "city": "彰化縣",
    "address": "彰化縣彰化市南郭路一段59號",
    "desc": "現代簡約蔬食，推薦麻辣系列麵食。",
    "lat": 24.072,
    "lng": 120.548,
    "link": "https://maps.google.com/?q=蒝味蔬食",
    "phone": "04-728-9597",
    "fb": "https://www.facebook.com/YuanWeiVeg/",
    "ig": "https://www.instagram.com/yuanweiveg/",
    "petFriendly": false
  },
  {
    "id": 64,
    "name": "督賀蔬苑",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.6,
    "reviews": 1300,
    "city": "南投縣",
    "address": "南投縣草屯鎮敦和路71號",
    "desc": "草屯精緻蔬食合菜，裝潢與口味均優。",
    "lat": 23.975,
    "lng": 120.68,
    "link": "https://maps.google.com/?q=督賀蔬苑",
    "phone": "04-9235-7166",
    "fb": "https://www.facebook.com/DuHeVeg/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 65,
    "name": "雅池閣蔬食餐廳",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.3,
    "reviews": 850,
    "city": "南投縣",
    "address": "南投縣埔里鎮南環路952號",
    "desc": "埔里地區大型蔬食，提供多樣台式素菜。",
    "lat": 23.955,
    "lng": 120.965,
    "link": "https://maps.google.com/?q=雅池閣蔬食餐廳",
    "phone": "04-9291-8228",
    "fb": "https://www.facebook.com/YaChiGe/",
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 66,
    "name": "一味無二綠食坊",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 1100,
    "city": "南投縣",
    "address": "南投縣魚池鄉魚池街853號",
    "desc": "日月潭周邊創意蔬食，在地食材入菜。觀光區建議出發前確認營業狀態。",
    "lat": 23.875,
    "lng": 120.925,
    "link": "https://maps.google.com/?q=一味無二綠食坊",
    "phone": "04-9289-8749",
    "fb": "https://www.facebook.com/YiWeiWuEr/",
    "ig": "https://www.instagram.com/yiweiwuer/",
    "petFriendly": true
  },
  {
    "id": 67,
    "name": "雪花素食",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.4,
    "reviews": 1450,
    "city": "南投縣",
    "address": "南投縣草屯鎮太平路二段318號",
    "desc": "在地超人氣平價素食，各式傳統麵羹美味。",
    "lat": 23.978,
    "lng": 120.682,
    "link": "https://maps.google.com/?q=雪花素食",
    "phone": "04-9232-9238",
    "fb": null,
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 68,
    "name": "妙觀音素食楊梅店",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.5,
    "reviews": 279,
    "city": "桃園市",
    "address": "桃園市楊梅區武營街26號",
    "desc": "平價美味的連鎖素食小吃，提供多樣化的麵食與小菜。",
    "lat": 24.908966,
    "lng": 121.144796,
    "link": "https://maps.google.com/?q=妙觀音素食楊梅店",
    "phone": "",
    "fb": null,
    "ig": null,
    "petFriendly": false
  },
  {
    "id": 69,
    "name": "惠圓蔬食便當",
    "types": [
      "純素",
      "奶素",
      "蛋素"
    ],
    "rating": 4.7,
    "reviews": 58,
    "city": "桃園市",
    "address": "桃園市楊梅區中山路121巷7號",
    "desc": "在地人推薦的健康蔬食便當，菜色豐富且少油少鹽。",
    "lat": 24.906843,
    "lng": 121.146609,
    "link": "https://maps.google.com/?q=惠圓蔬食便當",
    "phone": "",
    "fb": null,
    "ig": null,
    "petFriendly": false
  }
];
