import { Restaurant } from './types';

export const RESTAURANT_DATA: Restaurant[] = [
  // --- 台北市 (Taipei) ---
  {
    id: 1,
    name: "祥和蔬食料理（鎮江創始店）",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.4,
    reviews: 1638,
    city: "台北市",
    address: "台北市中正區鎮江街1巷1號",
    desc: "米其林必比登推薦，招牌菜有松露松柏長青、清蒸臭豆腐。",
    lat: 25.0435,
    lng: 121.5225,
    link: "https://maps.google.com/?q=祥和蔬食料理+鎮江創始店",
    phone: "02-2357-0377",
    fb: "https://www.facebook.com/serenity2005/",
    ig: "https://www.instagram.com/serenity_vegetarian/",
    petFriendly: false
  },
  {
    id: 2,
    name: "祥和蔬食料理（慶城店）",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 2109,
    city: "台北市",
    address: "台北市松山區南京東路三段303巷7弄7號",
    desc: "時尚明亮的素食空間，川式蔬食口味地道。",
    lat: 25.0535,
    lng: 121.5450,
    link: "https://maps.google.com/?q=祥和蔬食料理+慶城店",
    phone: "02-2546-6188",
    fb: "https://www.facebook.com/serenity2005/",
    ig: "https://www.instagram.com/serenity_vegetarian/",
    petFriendly: false
  },
  {
    id: 3,
    name: "小小樹食 Little Tree Food（大安店）",
    types: ["奶素", "蛋素", "五辛素"],
    rating: 4.3,
    reviews: 2622,
    city: "台北市",
    address: "台北市大安區大安路一段116巷17號",
    desc: "米其林綠星推薦，佛陀碗、皮蛋豆腐餃是必點。",
    lat: 25.0415,
    lng: 121.5460,
    link: "https://maps.google.com/?q=小小樹食+大安店",
    phone: "02-2778-2277",
    fb: "https://www.facebook.com/LittleTreeFood/",
    ig: "https://www.instagram.com/littletreefood/",
    petFriendly: true
  },
  {
    id: 4,
    name: "養心茶樓蔬食飲茶（松江本店）",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.3,
    reviews: 8459,
    city: "台北市",
    address: "台北市中山區松江路128號2樓",
    desc: "台北首家全蔬食港式飲茶，結合港點與精緻台菜。",
    lat: 25.0515,
    lng: 121.5325,
    link: "https://maps.google.com/?q=養心茶樓蔬食飲茶",
    phone: "02-2542-8828",
    fb: "https://www.facebook.com/yangshin2012/",
    ig: "https://www.instagram.com/yangshin_vege/",
    petFriendly: false
  },
  {
    id: 5,
    name: "不葷主義茶餐廳 台北店",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.9,
    reviews: 11602,
    city: "台北市",
    address: "台北市松山區南京東路三段275號2樓",
    desc: "精緻港式素食，環境高雅評價極高。",
    lat: 25.0520,
    lng: 121.5430,
    link: "https://maps.google.com/?q=不葷主義+台北店",
    phone: "02-2545-9977",
    fb: "https://www.facebook.com/veggienius21/",
    ig: "https://www.instagram.com/veggienius21/",
    petFriendly: false
  },
  {
    id: 6,
    name: "歡喜心集-台北南京店",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.8,
    reviews: 850,
    city: "台北市",
    address: "台北市松山區寧安街7巷2號",
    desc: "健康天然蔬食，環境舒適靜謐。",
    lat: 25.0505,
    lng: 121.5540,
    link: "https://maps.google.com/?q=歡喜心集+台北南京店",
    phone: "02-2577-5006",
    fb: "https://www.facebook.com/happyheartveg/",
    ig: null,
    petFriendly: false
  },
  {
    id: 7,
    name: "有哆創意蔬食洋食舘",
    types: ["奶素", "蛋素", "五辛素"],
    rating: 4.4,
    reviews: 1118,
    city: "台北市",
    address: "台北市松山區南京東路五段33號",
    desc: "歐式創意洋食，披薩與義大利麵口味多樣。",
    lat: 25.0510,
    lng: 121.5580,
    link: "https://maps.google.com/?q=有哆創意蔬食洋食舘",
    phone: "02-2769-3868",
    fb: null,
    ig: null,
    petFriendly: false
  },
  {
    id: 8,
    name: "心家純淨蔬食",
    types: ["純素"],
    rating: 4.8,
    reviews: 269,
    city: "台北市",
    address: "台北市松山區富錦街508號",
    desc: "溫馨小店，提供家常口味的全素料理。",
    lat: 25.0600,
    lng: 121.5620,
    link: "https://maps.google.com/?q=心家純淨蔬食",
    phone: "02-2767-5227",
    fb: null,
    ig: null,
    petFriendly: false
  },
  {
    id: 9,
    name: "蔬食百匯（首都松山店）",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.4,
    reviews: 1302,
    city: "台北市",
    address: "台北市松山區八德路四段658號",
    desc: "吃到飽百匯，菜色豐富。",
    lat: 25.0500,
    lng: 121.5760,
    link: "https://maps.google.com/?q=蔬食百匯+首都松山店",
    phone: "02-2507-1898",
    fb: null,
    ig: null,
    petFriendly: false
  },
  {
    id: 10,
    name: "果然匯 台北明曜店",
    types: ["純素", "奶素", "蛋素", "五辛素"],
    rating: 4.5,
    reviews: 8560,
    city: "台北市",
    address: "台北市大安區忠孝東路四段200號12樓",
    desc: "知名蔬食吃到飽，食材新鮮精緻。",
    lat: 25.0410,
    lng: 121.5510,
    link: "https://maps.google.com/?q=果然匯+台北明曜店",
    phone: "02-2771-8832",
    fb: "https://www.facebook.com/www.fruitfulfood.com.tw/",
    ig: "https://www.instagram.com/fruitfulfood_tw/",
    petFriendly: false
  },
  {
    id: 11,
    name: "BaganHood 蔬食餐酒館",
    types: ["純素"],
    rating: 4.7,
    reviews: 1850,
    city: "台北市",
    address: "台北市信義區忠孝東路四段553巷46弄11號",
    desc: "質感極佳的純素餐酒館，未來肉漢堡與特色調酒必試。",
    lat: 25.0427,
    lng: 121.5645,
    link: "https://maps.google.com/?q=BaganHood+蔬食餐酒館",
    phone: "02-3762-2557",
    fb: "https://www.facebook.com/BaganHood/",
    ig: "https://www.instagram.com/baganhood/",
    petFriendly: true
  },
  {
    id: 12,
    name: "Plants",
    types: ["純素"],
    rating: 4.6,
    reviews: 1420,
    city: "台北市",
    address: "台北市大安區復興南路一段253巷10號1樓",
    desc: "主打植物性、無麩質、全食物的健康美味料理。",
    lat: 25.0355,
    lng: 121.5443,
    link: "https://maps.google.com/?q=Plants+台北",
    phone: "02-2784-5677",
    fb: "https://www.facebook.com/plantseatery/",
    ig: "https://www.instagram.com/plantseatery/",
    petFriendly: true
  },
  {
    id: 13,
    name: "Miacucina（信義店）",
    types: ["奶素", "蛋素", "五辛素"],
    rating: 4.4,
    reviews: 3200,
    city: "台北市",
    address: "台北市信義區松壽路11號2樓",
    desc: "知名義式蔬食連鎖，沙拉、薄餅與義大利麵深受歡迎。",
    lat: 25.0363,
    lng: 121.5673,
    link: "https://maps.google.com/?q=Miacucina+信義店",
    phone: "02-2722-3120",
    fb: "https://www.facebook.com/Miacucinafamily/",
    ig: "https://www.instagram.com/miacucina_tw/",
    petFriendly: false
  },
  {
    id: 14,
    name: "無口小廚",
    types: ["純素"],
    rating: 4.8,
    reviews: 950,
    city: "台北市",
    address: "台北市大同區環河北路一段431號1樓",
    desc: "大稻埕文青純素拉麵與咖哩，燕麥奶湯頭濃郁。",
    lat: 25.0611,
    lng: 121.5088,
    link: "https://maps.google.com/?q=無口小廚",
    phone: "無提供",
    fb: "https://www.facebook.com/mukouchu/",
    ig: "https://www.instagram.com/mukouchu/",
    petFriendly: true
  },
  {
    id: 15,
    name: "三個傻瓜印度蔬食（公館店）",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 2100,
    city: "台北市",
    address: "台北市中正區羅斯福路三段283巷28號",
    desc: "道地印度香料蔬食，印度薄餅與咖哩風味絕佳。",
    lat: 25.0185,
    lng: 121.5324,
    link: "https://maps.google.com/?q=三個傻瓜印度蔬食+公館店",
    phone: "02-2369-9966",
    fb: "https://www.facebook.com/toastcurry1/",
    ig: null,
    petFriendly: false
  },
  {
    id: 16,
    name: "穗科手打烏龍麵（忠孝店）",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.4,
    reviews: 1800,
    city: "台北市",
    address: "台北市大安區忠孝東路四段216巷27弄3號",
    desc: "職人手打烏龍麵，日式清雅的純粹美味。",
    lat: 25.0402,
    lng: 121.5522,
    link: "https://maps.google.com/?q=穗科手打烏龍麵+忠孝店",
    phone: "02-2778-3737",
    fb: "https://www.facebook.com/HoshinaTW/",
    ig: "https://www.instagram.com/hoshina_tw/",
    petFriendly: false
  },
  {
    id: 17,
    name: "陽明春天（心苑）",
    types: ["純素"],
    rating: 4.6,
    reviews: 1250,
    city: "台北市",
    address: "台北市士林區菁山路119-1號",
    desc: "米其林綠星，結合茶道與藝術的無菜單高級蔬食。",
    lat: 25.1442,
    lng: 121.5631,
    link: "https://maps.google.com/?q=陽明春天+心苑",
    phone: "02-2862-0178",
    fb: "https://www.facebook.com/ymspring/",
    ig: "https://www.instagram.com/yangmingspring/",
    petFriendly: false
  },

  // --- 新北市 (New Taipei) ---
  {
    id: 18,
    name: "蓮荷蔬食（永和店）",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.1,
    reviews: 280,
    city: "新北市",
    address: "新北市永和區中正路410號",
    desc: "菜色多樣豐富，環境寬敞舒適，適合全家聚會。",
    lat: 25.0005,
    lng: 121.5175,
    link: "https://maps.google.com/?q=蓮荷蔬食+永和店",
    phone: "02-2921-2280",
    fb: null,
    ig: null,
    petFriendly: false
  },
  {
    id: 19,
    name: "貓嘰咕自家烘焙咖啡",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.7,
    reviews: 850,
    city: "新北市",
    address: "新北市板橋區文化路一段270巷3弄40號",
    desc: "溫馨的貓咪咖啡廳，提供美味的純素甜點與輕食。",
    lat: 25.0182,
    lng: 121.4623,
    link: "https://maps.google.com/?q=貓嘰咕自家烘焙咖啡",
    phone: "02-8259-5556",
    fb: "https://www.facebook.com/MaoJiGu/",
    ig: "https://www.instagram.com/maojigu/",
    petFriendly: true
  },
  {
    id: 20,
    name: "布佬廚房 Bruce's Kitchen",
    types: ["五辛素", "奶素", "蛋素"],
    rating: 4.3,
    reviews: 3100,
    city: "新北市",
    address: "新北市新店區車子路137號",
    desc: "隱身山林的義式蔬食，窯烤披薩與義大利麵是招牌。",
    lat: 24.9572,
    lng: 121.5005,
    link: "https://maps.google.com/?q=布佬廚房",
    phone: "02-8666-6181",
    fb: "https://www.facebook.com/bruceskitchentw/",
    ig: "https://www.instagram.com/bruceskitchentw/",
    petFriendly: true
  },
  {
    id: 21,
    name: "熱浪島南洋蔬食茶堂（林口店）",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 1600,
    city: "新北市",
    address: "新北市林口區惠民街2號",
    desc: "獨特的南洋風味蔬食，肉骨茶與叻沙麵必點。",
    lat: 25.0745,
    lng: 121.3712,
    link: "https://maps.google.com/?q=熱浪島南洋蔬食茶堂+林口店",
    phone: "02-2608-3082",
    fb: "https://www.facebook.com/pulau.redang3/",
    ig: null,
    petFriendly: false
  },
  {
    id: 22,
    name: "原素食府",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.2,
    reviews: 4500,
    city: "新北市",
    address: "新北市板橋區府中路29之2號4樓",
    desc: "板橋知名老字號蔬食百匯吃到飽，菜色百變。",
    lat: 25.0088,
    lng: 121.4595,
    link: "https://maps.google.com/?q=原素食府",
    phone: "02-2272-8999",
    fb: "https://www.facebook.com/yuanvegetarian/",
    ig: "https://www.instagram.com/yuanvegetarian/",
    petFriendly: false
  },
  {
    id: 23,
    name: "浣花草堂（中和店）",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.4,
    reviews: 920,
    city: "新北市",
    address: "新北市中和區連城路89巷5號",
    desc: "復古中式裝潢，提供平價美味的家常素食熱炒。",
    lat: 25.0012,
    lng: 121.4923,
    link: "https://maps.google.com/?q=浣花草堂+中和店",
    phone: "02-8245-8718",
    fb: "https://www.facebook.com/HuanHuaCaoTang/",
    ig: null,
    petFriendly: false
  },

  // --- 桃園市 (Taoyuan) ---
  {
    id: 24,
    name: "Monday 蔬食料理（桃園店）",
    types: ["奶素", "蛋素", "五辛素"],
    rating: 4.9,
    reviews: 1704,
    city: "桃園市",
    address: "桃園市桃園區大有路648號",
    desc: "未來肉漢堡與燉飯系列廣受好評，評價極高。",
    lat: 25.0150,
    lng: 121.3210,
    link: "https://maps.google.com/?q=Monday+蔬食料理",
    phone: "03-355-6611",
    fb: "https://www.facebook.com/mondayvegetarian/",
    ig: null,
    petFriendly: true
  },
  {
    id: 25,
    name: "入木三分 無菜單蔬食",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.6,
    reviews: 850,
    city: "桃園市",
    address: "桃園市龍潭區新龍路62號",
    desc: "採預約制的精緻無菜單料理，環境清幽雅致。",
    lat: 24.8621,
    lng: 121.2134,
    link: "https://maps.google.com/?q=入木三分+無菜單蔬食",
    phone: "03-479-0220",
    fb: "https://www.facebook.com/rumusanfen/",
    ig: null,
    petFriendly: false
  },
  {
    id: 26,
    name: "梳子餐廳 Salong",
    types: ["五辛素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 1200,
    city: "桃園市",
    address: "桃園市桃園區新埔六街89號",
    desc: "網美風川味蔬食，裝潢華麗，餐點口味創新。",
    lat: 25.0155,
    lng: 121.3012,
    link: "https://maps.google.com/?q=梳子餐廳",
    phone: "03-315-1571",
    fb: "https://www.facebook.com/salong.restaurant/",
    ig: "https://www.instagram.com/salong_restaurant/",
    petFriendly: false
  },
  {
    id: 27,
    name: "艾維農歐風素食",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.7,
    reviews: 680,
    city: "桃園市",
    address: "桃園市桃園區大業路一段292號1樓",
    desc: "結合法式擺盤與台灣在地食材的高級歐風蔬食。",
    lat: 25.0088,
    lng: 121.3155,
    link: "https://maps.google.com/?q=艾維農歐風素食",
    phone: "03-358-1350",
    fb: "https://www.facebook.com/avignonrestaurant/",
    ig: "https://www.instagram.com/avignon_veg/",
    petFriendly: false
  },
  {
    id: 28,
    name: "善果林蔬食",
    types: ["純素"],
    rating: 4.4,
    reviews: 550,
    city: "桃園市",
    address: "桃園市中壢區環北路400號",
    desc: "溫馨平價的全素餐館，麵食與小菜選擇豐富。",
    lat: 24.9622,
    lng: 121.2211,
    link: "https://maps.google.com/?q=善果林蔬食",
    phone: "03-422-2220",
    fb: null,
    ig: null,
    petFriendly: false
  },
  {
    id: 29,
    name: "Veggie Joy 蔬食樂",
    types: ["純素", "五辛素"],
    rating: 4.6,
    reviews: 720,
    city: "桃園市",
    address: "桃園市蘆竹區南崁路一段112號",
    desc: "主打健康輕食、沙拉與植物肉漢堡。",
    lat: 25.0411,
    lng: 121.2955,
    link: "https://maps.google.com/?q=Veggie+Joy+蔬食樂",
    phone: "03-322-2220",
    fb: "https://www.facebook.com/veggiejoytw/",
    ig: "https://www.instagram.com/veggiejoytw/",
    petFriendly: true
  },
  // --- 第一階段補充 (Phase 1 Additions) ---
  {
    id: 30,
    name: "上善豆家 Deliysys",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.3,
    reviews: 2450,
    city: "台北市",
    address: "台北市大安區復興南路一段107巷16號",
    desc: "文青風豆製品主題蔬食，冰花煎餃與手作豆花必吃。",
    lat: 25.0425,
    lng: 121.5438,
    link: "https://maps.google.com/?q=上善豆家",
    phone: "02-2771-8937",
    fb: "https://www.facebook.com/delisys.tw/",
    ig: "https://www.instagram.com/delisys.tw/",
    petFriendly: false
  },
  {
    id: 31,
    name: "蔬慕 Vegan Amore",
    types: ["純素", "五辛素"],
    rating: 4.6,
    reviews: 1320,
    city: "台北市",
    address: "台北市大同區承德路一段1號3F",
    desc: "京站內的時尚純素西式餐廳，燕麥奶義大利麵與漢堡極佳。",
    lat: 25.0494,
    lng: 121.5168,
    link: "https://maps.google.com/?q=蔬慕+Vegan+Amore",
    phone: "02-2555-6090",
    fb: "https://www.facebook.com/veganamore.tw/",
    ig: "https://www.instagram.com/veganamore.tw/",
    petFriendly: false
  },
  {
    id: 32,
    name: "Herbivore 復古蔬食",
    types: ["純素", "五辛素"],
    rating: 4.4,
    reviews: 980,
    city: "台北市",
    address: "台北市信義區松壽路21號2樓",
    desc: "Miacucina 姊妹品牌，主打異國風純素料理，咖哩與沙拉份量足。",
    lat: 25.0358,
    lng: 121.5675,
    link: "https://maps.google.com/?q=Herbivore",
    phone: "02-2723-5368",
    fb: "https://www.facebook.com/Herbivore.tw/",
    ig: "https://www.instagram.com/herbivore_tw/",
    petFriendly: false
  },
  {
    id: 33,
    name: "果然匯 板橋店",
    types: ["純素", "奶素", "蛋素", "五辛素"],
    rating: 4.6,
    reviews: 4100,
    city: "新北市",
    address: "新北市板橋區中山路一段152號11樓",
    desc: "新北最受歡迎的蔬食吃到飽，現做義大利麵與猴頭菇排是亮點。",
    lat: 25.0118,
    lng: 121.4628,
    link: "https://maps.google.com/?q=果然匯+板橋店",
    phone: "02-2956-2888",
    fb: "https://www.facebook.com/www.fruitfulfood.com.tw/",
    ig: "https://www.instagram.com/fruitfulfood_tw/",
    petFriendly: false
  },
  {
    id: 34,
    name: "寬心園 板橋中山店",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 1850,
    city: "新北市",
    address: "新北市板橋區中山路一段158號",
    desc: "老字號精緻和風蔬食套餐，養生且食材講究。",
    lat: 25.0115,
    lng: 121.4630,
    link: "https://maps.google.com/?q=寬心園+板橋中山店",
    phone: "02-8953-2983",
    fb: "https://www.facebook.com/easyhouse1108/",
    ig: null,
    petFriendly: false
  },
  {
    id: 35,
    name: "漢來蔬食 桃園店",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.6,
    reviews: 2200,
    city: "桃園市",
    address: "桃園市蘆竹區南崁路一段112號6樓",
    desc: "台茂購物中心內的五星級蔬食港點，藜麥八寶菜飯必點。",
    lat: 25.0411,
    lng: 121.2955,
    link: "https://maps.google.com/?q=漢來蔬食+桃園店",
    phone: "03-312-5222",
    fb: "https://www.facebook.com/hilaivegetarian/",
    ig: null,
    petFriendly: false
  },
  {
    id: 36,
    name: "果然匯 桃園統領店",
    types: ["純素", "奶素", "蛋素", "五辛素"],
    rating: 4.6,
    reviews: 3500,
    city: "桃園市",
    address: "桃園市桃園區中正路61號7樓",
    desc: "桃園火車站前的高人氣蔬食百匯，餐點選擇極多。",
    lat: 24.9935,
    lng: 121.3138,
    link: "https://maps.google.com/?q=果然匯+桃園統領店",
    phone: "03-333-9666",
    fb: "https://www.facebook.com/www.fruitfulfood.com.tw/",
    ig: "https://www.instagram.com/fruitfulfood_tw/",
    petFriendly: false
  },
  // --- 第二階段 (Phase 2): 新竹、苗栗、宜蘭 ---
  {
    id: 37,
    name: "籽田野菜屋",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.6,
    reviews: 1250,
    city: "新竹縣",
    address: "新竹縣竹北市高鐵二路136號",
    desc: "日式文青風蔬食，招牌胡麻拉麵與烤糰子極具特色。",
    lat: 24.8080,
    lng: 121.0405,
    link: "https://maps.google.com/?q=籽田野菜屋",
    phone: "03-668-5688",
    fb: "https://www.facebook.com/seed.veg/",
    ig: null,
    petFriendly: false
  },
  {
    id: 38,
    name: "善菓堂 SHAN GUO TANG",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 950,
    city: "新竹縣",
    address: "新竹縣竹北市莊敬南路188號1樓",
    desc: "禪風精緻中式蔬食，蘿蔔糕與各式手工點心必點。",
    lat: 24.8165,
    lng: 121.0250,
    link: "https://maps.google.com/?q=善菓堂",
    phone: "03-667-5955",
    fb: "https://www.facebook.com/shanguotang/",
    ig: "https://www.instagram.com/shanguotang/",
    petFriendly: false
  },
  {
    id: 39,
    name: "井町日式蔬食-新大同店",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.4,
    reviews: 1500,
    city: "新竹市",
    address: "新竹市東區大同路136號",
    desc: "平價美味的日式蔬食，冷麵與炸物拼盤深受年輕人喜愛。",
    lat: 24.8055,
    lng: 120.9685,
    link: "https://maps.google.com/?q=井町日式蔬食+新大同店",
    phone: "03-525-3158",
    fb: "https://www.facebook.com/JingTingVeg/",
    ig: null,
    petFriendly: false
  },
  {
    id: 40,
    name: "輕揚 Veggie Delight",
    types: ["純素", "五辛素"],
    rating: 4.5,
    reviews: 880,
    city: "新竹縣",
    address: "新竹縣竹北市科大一路130號",
    desc: "網美風創意蔬食，植物肉漢堡與健康沙拉碗份量十足。",
    lat: 24.8235,
    lng: 121.0110,
    link: "https://maps.google.com/?q=輕揚+Veggie+Delight",
    phone: "03-558-5580",
    fb: "https://www.facebook.com/veggiedelight.tw/",
    ig: "https://www.instagram.com/veggiedelight.tw/",
    petFriendly: true
  },
  {
    id: 41,
    name: "蔬適圈",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.7,
    reviews: 420,
    city: "新竹市",
    address: "新竹市北區北大路285-1號",
    desc: "健康無負擔的蔬食簡餐，食材新鮮，口味清爽。",
    lat: 24.8112,
    lng: 120.9650,
    link: "https://maps.google.com/?q=蔬適圈",
    phone: "03-522-0866",
    fb: "https://www.facebook.com/vegecircle/",
    ig: null,
    petFriendly: false
  },
  {
    id: 42,
    name: "寬心園 新竹竹北店",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 1650,
    city: "新竹縣",
    address: "新竹縣竹北市莊敬二街8號",
    desc: "知名高級蔬食連鎖，提供精緻和風蔬食套餐，適合聚餐。",
    lat: 24.8250,
    lng: 121.0255,
    link: "https://maps.google.com/?q=寬心園+新竹竹北店",
    phone: "03-550-9716",
    fb: "https://www.facebook.com/easyhouse1108/",
    ig: null,
    petFriendly: false
  },
  {
    id: 43,
    name: "卓也小屋 蔬食餐廳",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.4,
    reviews: 5600,
    city: "苗栗縣",
    address: "苗栗縣三義鄉雙潭村13鄰崩山下1-5號",
    desc: "隱身山林的知名客家景觀蔬食，提供養生藥膳鍋與在地食材。",
    lat: 24.3885,
    lng: 120.7980,
    link: "https://maps.google.com/?q=卓也小屋+蔬食餐廳",
    phone: "03-787-9198",
    fb: "https://www.facebook.com/joyesanyi/",
    ig: "https://www.instagram.com/joyesanyi/",
    petFriendly: true
  },
  {
    id: 44,
    name: "禪廚蔬食餐廳",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.6,
    reviews: 1800,
    city: "苗栗縣",
    address: "苗栗縣頭份市中央路726號",
    desc: "苗栗高人氣創意中式蔬食，合菜精緻，適合家族聚餐。",
    lat: 24.6935,
    lng: 120.9020,
    link: "https://maps.google.com/?q=禪廚蔬食餐廳",
    phone: "03-768-8829",
    fb: "https://www.facebook.com/ZenKitchenVeg/",
    ig: null,
    petFriendly: false
  },
  {
    id: 45,
    name: "滴水坊-大明寺",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 350,
    city: "苗栗縣",
    address: "苗栗縣苗栗市經國路二段485號",
    desc: "佛光山體系，環境清幽，提供平價美味的素麵與簡餐。",
    lat: 24.5710,
    lng: 120.8250,
    link: "https://maps.google.com/?q=大明寺+滴水坊",
    phone: "03-732-7401",
    fb: null,
    ig: null,
    petFriendly: false
  },
  {
    id: 46,
    name: "荷塘居",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.3,
    reviews: 1200,
    city: "苗栗縣",
    address: "苗栗縣公館鄉館南村13鄰332號",
    desc: "優美的庭園景觀餐廳，提供精緻的蔬食套餐與下午茶。",
    lat: 24.4980,
    lng: 120.8215,
    link: "https://maps.google.com/?q=荷塘居",
    phone: "03-723-3456",
    fb: "https://www.facebook.com/hetangju/",
    ig: null,
    petFriendly: false
  },
  {
    id: 47,
    name: "曙光蔬食",
    types: ["純素", "五辛素"],
    rating: 4.7,
    reviews: 650,
    city: "宜蘭縣",
    address: "宜蘭縣羅東鎮中正北路111號",
    desc: "羅東高評價義式蔬食，燉飯與義大利麵口味濃郁創新。",
    lat: 24.6815,
    lng: 121.7725,
    link: "https://maps.google.com/?q=曙光蔬食",
    phone: "03-955-6888",
    fb: "https://www.facebook.com/DawnVegan/",
    ig: "https://www.instagram.com/dawnvegan/",
    petFriendly: false
  },
  {
    id: 48,
    name: "綠緣居蔬食館",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.4,
    reviews: 520,
    city: "宜蘭縣",
    address: "宜蘭縣宜蘭市女中路三段111號",
    desc: "宜蘭在地老字號中式蔬食，菜色豐富，價格親民。",
    lat: 24.7485,
    lng: 121.7480,
    link: "https://maps.google.com/?q=綠緣居蔬食館",
    phone: "03-936-6888",
    fb: null,
    ig: null,
    petFriendly: false
  },
  {
    id: 49,
    name: "幸福蝸牛",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.6,
    reviews: 480,
    city: "宜蘭縣",
    address: "宜蘭縣宜蘭市農權路三段163巷11號",
    desc: "溫馨家常的蔬食小館，提供健康美味的定食與火鍋。",
    lat: 24.7460,
    lng: 121.7450,
    link: "https://maps.google.com/?q=幸福蝸牛",
    phone: "03-936-6688",
    fb: "https://www.facebook.com/HappySnailVeg/",
    ig: null,
    petFriendly: false
  },
  {
    id: 50,
    name: "一簞食 - 蔬食x生活",
    types: ["純素", "五辛素"],
    rating: 4.8,
    reviews: 320,
    city: "宜蘭縣",
    address: "宜蘭縣員山鄉尚深路122號",
    desc: "深溝村的文青小店，使用在地小農食材的純粹蔬食。",
    lat: 24.7350,
    lng: 121.7200,
    link: "https://maps.google.com/?q=一簞食",
    phone: "無提供",
    fb: "https://www.facebook.com/yidanshi/",
    ig: "https://www.instagram.com/yidanshi/",
    petFriendly: true
  },
  {
    id: 51,
    name: "佛光山蘭陽別院 滴水坊",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 680,
    city: "宜蘭縣",
    address: "宜蘭縣宜蘭市中山路三段257號1樓",
    desc: "環境莊嚴舒適，提供平價好吃的素燥飯與各式麵食。",
    lat: 24.7615,
    lng: 121.7550,
    link: "https://maps.google.com/?q=蘭陽別院+滴水坊",
    phone: "03-933-3888",
    fb: null,
    ig: null,
    petFriendly: false
  },
  // --- 第三階段 (Phase 3): 台中、彰化、南投 ---
  {
    id: 52,
    name: "不葷主義茶餐廳 台中店",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.8,
    reviews: 8500,
    city: "台中市",
    address: "台中市南屯區公益路二段21號",
    desc: "台中超高人氣素食港點，裝潢高雅，流沙包與絲瓜湯包必點。",
    lat: 24.1505,
    lng: 120.6500,
    link: "https://maps.google.com/?q=不葷主義茶餐廳+台中店",
    phone: "04-2328-8111",
    fb: "https://www.facebook.com/veggienius21/",
    ig: "https://www.instagram.com/veggienius21/",
    petFriendly: false
  },
  {
    id: 53,
    name: "曙光居",
    types: ["純素"],
    rating: 4.6,
    reviews: 1200,
    city: "台中市",
    address: "台中市西屯區大墩十八街104號",
    desc: "米其林必比登推薦，純素手作麵食與香辣麵令人驚豔。",
    lat: 24.1580,
    lng: 120.6485,
    link: "https://maps.google.com/?q=曙光居",
    phone: "04-2329-2322",
    fb: "https://www.facebook.com/shuguangju/",
    ig: null,
    petFriendly: false
  },
  {
    id: 54,
    name: "將進酒 頂級蔬食燒肉殿",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.7,
    reviews: 2100,
    city: "台中市",
    address: "台中市西區精誠五街27號",
    desc: "全台首創頂級蔬食燒肉，提供多樣化植物肉與精緻烤物。",
    lat: 24.1540,
    lng: 120.6560,
    link: "https://maps.google.com/?q=將進酒+頂級蔬食燒肉殿",
    phone: "04-2327-8012",
    fb: "https://www.facebook.com/vgbbq/",
    ig: "https://www.instagram.com/vgbbq/",
    petFriendly: false
  },
  {
    id: 55,
    name: "Enrich restaurant & café",
    types: ["純素", "五辛素"],
    rating: 4.6,
    reviews: 1550,
    city: "台中市",
    address: "台中市西屯區大墩二十街111號",
    desc: "創意西式蔬食，松露燉飯與特色沙拉深受年輕族群喜愛。",
    lat: 24.1590,
    lng: 120.6505,
    link: "https://maps.google.com/?q=Enrich+restaurant",
    phone: "04-2310-8386",
    fb: "https://www.facebook.com/enrichrestaurant/",
    ig: "https://www.instagram.com/enrichrestaurant/",
    petFriendly: true
  },
  {
    id: 56,
    name: "養素庭迴轉火車蔬食火鍋",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 3200,
    city: "台中市",
    address: "台中市北屯區崇德路二段208號",
    desc: "趣味十足的迴轉蔬食火鍋吃到飽，湯頭多樣，食材新鮮。",
    lat: 24.1750,
    lng: 120.6850,
    link: "https://maps.google.com/?q=養素庭迴轉火車蔬食火鍋",
    phone: "04-2241-1585",
    fb: "https://www.facebook.com/yangsuting/",
    ig: null,
    petFriendly: false
  },
  {
    id: 57,
    name: "菜市場 Tsai Chi Tsang",
    types: ["純素"],
    rating: 4.7,
    reviews: 650,
    city: "台中市",
    address: "台中市西區向上北路167號",
    desc: "米其林綠星推薦，嚴選台灣在地小農食材的純素無菜單料理。",
    lat: 24.1465,
    lng: 120.6620,
    link: "https://maps.google.com/?q=菜市場+Tsai+Chi+Tsang",
    phone: "04-2301-6873",
    fb: "https://www.facebook.com/tsaichitsang/",
    ig: "https://www.instagram.com/tsaichitsang/",
    petFriendly: false
  },
  {
    id: 58,
    name: "漢來蔬食 台中廣三SOGO店",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 1900,
    city: "台中市",
    address: "台中市西區台灣大道二段459號16樓",
    desc: "五星級精緻蔬食港點，千層蘿蔔絲酥角與藜麥八寶菜飯必嚐。",
    lat: 24.1555,
    lng: 120.6625,
    link: "https://maps.google.com/?q=漢來蔬食+台中廣三SOGO店",
    phone: "04-2325-3888",
    fb: "https://www.facebook.com/hilaivegetarian/",
    ig: null,
    petFriendly: false
  },
  {
    id: 59,
    name: "斐得蔬食 秀泰台中站前店",
    types: ["純素", "五辛素"],
    rating: 4.8,
    reviews: 2800,
    city: "台中市",
    address: "台中市東區南京路66號3樓",
    desc: "高評價創意蔬食，提供多國風味料理，義大利麵與披薩極佳。",
    lat: 24.1365,
    lng: 120.6880,
    link: "https://maps.google.com/?q=斐得蔬食+秀泰台中站前店",
    phone: "04-2215-0376",
    fb: "https://www.facebook.com/VerdureRestaurant/",
    ig: "https://www.instagram.com/verdure_restaurant/",
    petFriendly: false
  },
  {
    id: 60,
    name: "林家素食",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.3,
    reviews: 1100,
    city: "彰化縣",
    address: "彰化縣彰化市永安街252號",
    desc: "彰化在地知名老店，素圓、乾麵與各式滷味價格親民又美味。",
    lat: 24.0830,
    lng: 120.5420,
    link: "https://maps.google.com/?q=林家素食",
    phone: "04-726-8627",
    fb: null,
    ig: null,
    petFriendly: false
  },
  {
    id: 61,
    name: "清心緣蔬食坊",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 1650,
    city: "彰化縣",
    address: "彰化縣彰化市中華西路165號",
    desc: "高CP值蔬食吃到飽，菜色豐富多變，是在地人聚餐首選。",
    lat: 24.0750,
    lng: 120.5300,
    link: "https://maps.google.com/?q=清心緣蔬食坊",
    phone: "04-762-2399",
    fb: "https://www.facebook.com/QingXinYuan/",
    ig: null,
    petFriendly: false
  },
  {
    id: 62,
    name: "淘米樂蔬食園地",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.4,
    reviews: 950,
    city: "彰化縣",
    address: "彰化縣彰化市寶山路802號",
    desc: "隱身八卦山麓的庭園蔬食吃到飽，環境清幽，食材天然。",
    lat: 24.0650,
    lng: 120.5550,
    link: "https://maps.google.com/?q=淘米樂蔬食園地",
    phone: "04-728-7132",
    fb: "https://www.facebook.com/taomile/",
    ig: null,
    petFriendly: false
  },
  {
    id: 63,
    name: "蒝味蔬食",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.6,
    reviews: 820,
    city: "彰化縣",
    address: "彰化縣彰化市南郭路一段59號",
    desc: "文青風格的蔬食小館，麻辣臭豆腐與各式特色湯麵廣受好評。",
    lat: 24.0720,
    lng: 120.5480,
    link: "https://maps.google.com/?q=蒝味蔬食",
    phone: "04-728-9597",
    fb: "https://www.facebook.com/YuanWeiVeg/",
    ig: "https://www.instagram.com/yuanweiveg/",
    petFriendly: false
  },
  {
    id: 64,
    name: "督賀蔬苑",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.6,
    reviews: 1300,
    city: "南投縣",
    address: "南投縣草屯鎮敦和路71號",
    desc: "草屯精緻中式蔬食合菜，裝潢典雅，適合家族與節慶聚餐。",
    lat: 23.9750,
    lng: 120.6800,
    link: "https://maps.google.com/?q=督賀蔬苑",
    phone: "04-9235-7166",
    fb: "https://www.facebook.com/DuHeVeg/",
    ig: null,
    petFriendly: false
  },
  {
    id: 65,
    name: "雅池閣蔬食餐廳",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.3,
    reviews: 850,
    city: "南投縣",
    address: "南投縣埔里鎮南環路952號",
    desc: "埔里知名大型蔬食餐廳，提供豐富的合菜與在地特色料理。",
    lat: 23.9550,
    lng: 120.9650,
    link: "https://maps.google.com/?q=雅池閣蔬食餐廳",
    phone: "04-9291-8228",
    fb: "https://www.facebook.com/YaChiGe/",
    ig: null,
    petFriendly: false
  },
  {
    id: 66,
    name: "一味無二綠食坊",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.5,
    reviews: 1100,
    city: "南投縣",
    address: "南投縣魚池鄉魚池街853號",
    desc: "日月潭附近的質感綠色餐廳，結合在地食材的創意蔬食。",
    lat: 23.8750,
    lng: 120.9250,
    link: "https://maps.google.com/?q=一味無二綠食坊",
    phone: "04-9289-8749",
    fb: "https://www.facebook.com/YiWeiWuEr/",
    ig: "https://www.instagram.com/yiweiwuer/",
    petFriendly: true
  },
  {
    id: 67,
    name: "雪花素食",
    types: ["純素", "奶素", "蛋素"],
    rating: 4.4,
    reviews: 1450,
    city: "南投縣",
    address: "南投縣草屯鎮太平路二段318號",
    desc: "草屯在地人氣平價素食，各式麵食、羹湯與小菜選擇多樣。",
    lat: 23.9780,
    lng: 120.6820,
    link: "https://maps.google.com/?q=雪花素食",
    phone: "04-9232-9238",
    fb: null,
    ig: null,
    petFriendly: false
  }
];
